platform :ios,'6.0'
pod 'Nimbus', '~> 1.2.0'
pod 'AFNetworking', '~> 2.2.3'
pod 'MBProgressHUD'
pod 'MTStatusBarOverlay'
pod 'SSKeychain'
pod 'HPGrowingTextView'
pod 'SDSegmentedControl'
pod 'NSStringEmojize'
pod 'LTUpdate', '~> 0.0.2'
pod 'RTagCloudView'
pod 'NSAttributedStringMarkdownParser', '~> 0.0.1'
