platform :ios,'6.0'
pod 'Nimbus', '~> 1.0.0'
pod 'AFNetworking', '~> 1.3.3'
pod 'JSONKit'
pod 'MBProgressHUD'
pod 'MTStatusBarOverlay'
pod 'PPRevealSideViewController'
pod 'SSKeychain'
pod 'HPGrowingTextView'
pod 'SDSegmentedControl'
pod 'NSStringEmojize'
pod 'LTUpdate', '~> 0.0.2'
pod 'RTagCloudView'